version: '3.3'

volumes:
  zookeeper-data:
  zookeeper-tx-log:
  kafka-data:
  mariadb-data:
  elastic-search-data:

services:

  db:
    image: mariadb:10.3.5
    hostname: db
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2G
